ServerName localhost
ServerTokens Prod
ServerSignature Off
Timeout 120
KeepAliveTimeout 2

<IfModule mpm_prefork_module>
    StartServers 2
    MinSpareServers 2
    MaxSpareServers 4
    MaxRequestWorkers 8
    MaxConnectionsPerChild 1000
</IfModule>

<VirtualHost *:8080>
    DocumentRoot /var/www/html/public
    DirectoryIndex disabled
    DirectoryIndex index.html
    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined

    <Directory /var/www/html/public>
        AllowOverride None
        Options -Indexes -MultiViews +FollowSymLinks
        Require all granted

        <FilesMatch "^\.">
            Require all denied
        </FilesMatch>

        RewriteEngine On
        RewriteCond %{HTTP:Authorization} .
        RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
        RewriteCond %{HTTP:X-XSRF-Token} .
        RewriteRule .* - [E=HTTP_X_XSRF_TOKEN:%{HTTP:X-XSRF-Token}]
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.php [END]
    </Directory>

    Header always set X-Content-Type-Options "nosniff"
</VirtualHost>
